# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'  Calculate criterion quantiles
#'
#' 'criterionquantiles' lets you calculate the criterion quantiles using a bootstrap.
#'
#' @param y Response variable vector.
#' @param X Covariates matrix.
#' @param level Vector of levels.
#' @param estimator_grid Lasso estimator grid matrix.
#' @param nbr_bootstraps Number of bootstrap simulations. Defaults to 1000.
#' @param w Number of blocks. If bs_type = "multiplier" then w is not applicable. If bs_type = "stationary", then w is the mean of number of blocks used for each bootstrap sample. Defaults to 10.
#' @param bs_type Type of bootstrap technique to be used. The following methods are available for use: "multiplier", "stationary_block" and "moving_block". Any specified character length is sufficient. Defaults to "multiplier".
#' @return criterion_quantiles Returns a matrix of quantile at each level with each row being the different values from the grid of lambdas.
#'
#'@examples
#'lasso <- lasso(Y = Y,
#'                X = X,
#'                out = 1,
#'                numlam = 100,
#'                maxIter = 1e10,
#'                opTol = 1e-10,
#'                standardize = 0)
#'
#'#Remove equidistant lambda row
#'BETA <- lasso %>% head(-1)
#'
#'criterion_q <- criterionquantiles(Y = Y,
#'                                   X = X,
#'                                   level = c(0.90, 0.95, 0.99),
#'                                   estimator_grid = BETA,
#'                                   nbr_bootstraps = 10000,
#'                                   w = 20,
#'                                   bs_type = "det")
criterionquantiles <- function(y, X, level, estimator_grid, nbr_bootstraps = 1000L, w = 10L, bs_type = "multiplier") {
    .Call(`_LassoBoot_criterionquantiles`, y, X, level, estimator_grid, nbr_bootstraps, w, bs_type)
}

#'  Compute lasso
#'
#' 'lasso' lets you compute the lasso estimator using the coordinate descent algorithm.
#'
#' @param Y Response variable vector.
#' @param X Covariates matrix.
#' @param out 1: Outputs betas. 2: Outputs residuals.
#' @param numlam Number of lambdas in equidistant lambda grid.
#' @param maxIter Maximum number of iterations.
#' @param optTol The optimization tolerance as an indicatin for convergence.
#' @param standardize Whether or not data should be standardized.
#' @return lasso Returns lasso estimates for each lambda.
#'
#'@examples
#'BETA <- lasso(X = X, Y = Y, out = 1)
#'
lasso <- function(X, Y, out, numlam, maxIter, optTol, standardize) {
    .Call(`_LassoBoot_lasso`, X, Y, out, numlam, maxIter, optTol, standardize)
}

#'  Moving Block Bootstrap
#'
#' 'moving_block_bootstrap' lets you compute moving block bootstrap samples of your data.
#'
#' @param data Data to bootstrap
#' @param B Number of bootstrap samples. Defaults to 1000.
#' @param w Number of blocks. Defaults to 10.
#' @return Returns matrix of n*(B*p) dimensions.
#'
#'@examples
#'bs_data <- block_bootstrap(data)
#'
moving_block_bootstrap <- function(data, B = 1000L, w = 10L) {
    .Call(`_LassoBoot_moving_block_bootstrap`, data, B, w)
}

#'  Calculate the estimated quantiles of the effective noise
#'
#' 'quantileestimated' lets you calculate the estimated quantiles using the criterion quantiles.
#'
#' @param Y Response variable vector.
#' @param X Covariates matrix.
#' @param level Vector of levels.
#' @param estimator_grid Lasso estimator grid matrix.
#' @param nbr_bootstraps Number of bootstrap simulations. Defaults to 1000.
#' @param criterion_quantiles The criterion quantiles computed using the 'criterionquantiles' function.
#' @return quantilesestimated Returns the value of the estimated quantile of the Lasso's effective noise.
#'
#'@examples
#'lasso <- lasso(Y = Y,
#'                X = X,
#'                out = 1,
#'                numlam = 100,
#'                maxIter = 1e10,
#'                opTol = 1e-10,
#'                standardize = 0)
#'
#'#Remove equidistant lambda row
#'BETA <- lasso %>% head(-1)
#'
#'criterion_q <- criterionquantiles(Y = Y,
#'                                   X = X,
#'                                   level = c(0.90, 0.95, 0.99),
#'                                   estimator_grid = BETA,
#'                                   nbr_bootstraps = 10000,
#'                                   w = 20,
#'                                   bs_type = "stationary_block")
#'quantile_e <- quantileestimated(Y = Y,
#'                                 X = X,
#'                                 level = 0.95,
#'                                 estimator_grid,
#'                                 criterionquantiles = criterion_q)
#'
#'
quantileestimated <- function(Y, X, level, lambda_grid, criterion_quantiles) {
    .Call(`_LassoBoot_quantileestimated`, Y, X, level, lambda_grid, criterion_quantiles)
}

#'  Calculates the oracle quantile
#'
#' 'quantileoracle' lets you calculate the oracle quantiles with simulated data.
#'
#' @param n  Number of observations to generate for the simulated data.
#' @param p  Number of covariates to generate for the simulated data.
#' @param kappa Covariance between the covariates.
#' @param rho The coefficient in the AR(1)-process. Controls the dependence of observation at time t to the observation at time t-1.
#' @param level Vector of levels.
#' @param sdev The specified standard deviation for the noise.
#' @param nbr_bootstraps Number of bootstrap simulations. Defaults to 1000.
#' @return quantileoracle Returns the value of the approximated quantile of the lasso's effective noise.
#'
#'@examples
#'
#'quantileoracle(n = 500,
#'                p = 1000,
#'                kappa = 0.25,
#'                rho = 0.95
#'                level = c(0.95, 0.99),
#'                sdev = 1)
#'
quantileoracle <- function(n, p, kappa, rho, level, sdev = 1, nbr_bootstraps = 1000L) {
    .Call(`_LassoBoot_quantileoracle`, n, p, kappa, rho, level, sdev, nbr_bootstraps)
}

#'  Calculates the oracle quantile
#'
#' 'quantileoracleconditinal' lets you calculate the oracle quantiles dependent on X.
#'
#' @param X Covariates matrix.
#' @param level Vector of levels.
#' @param sdev The specified standard deviation for the noise.
#' @param nbr_bootstraps Number of bootstrap simulations. Defaults to 1000.
#' @return quantileoracleconditional Returns the value of the approximated quantile of the lasso's effective noise dependent on X.
#'
#'@examples
#'
#'quantileoracleconditional(X = X,
#'                           level = c(0.95, 0.99),
#'                           sdev = 1)
#'
quantileoracleconditional <- function(X, level, sdev = 1, nbr_bootstraps = 1000L) {
    .Call(`_LassoBoot_quantileoracleconditional`, X, level, sdev, nbr_bootstraps)
}

#'  Stationary Block Bootstrap
#'
#' 'stationary_block_bootstrap' lets you compute moving block bootstrap samples of your data.
#'
#' @param data Data to bootstrap
#' @param B Number of bootstrap samples. Defaults to 1000.
#' @param w Mean number of blocks. Defaults to 10.
#' @return Returns matrix of n*(B*p) dimensions.
#'
#'@examples
#'bs_data <- stationary_block_bootstrap(data)
#'
stationary_block_bootstrap <- function(data, B = 1000L, w = 10L) {
    .Call(`_LassoBoot_stationary_block_bootstrap`, data, B, w)
}

